# python-psutil is required by dconf
- name: Install python-psutil
  apt:
    name: python-psutil
  become: yes

- name: Enable Night Light
  dconf:
    key: "/org/gnome/calendar/follow-night-light"
    value: "true"
    state: present
