---
- name: Define DOCKER_CONFIG location
  lineinfile:
    dest: "{{ xdg.XDG_CONFIG_HOME }}/zsh/.zshrc"
    line: export DOCKER_CONFIG={{ xdg.XDG_CONFIG_HOME }}/docker

- name: Create Docker config folder
  file:
    path: "{{ xdg.XDG_CONFIG_HOME }}/docker"
    state: directory

- name: Copy Docker config
  copy:
    src: docker/config
    dest: "{{ xdg.XDG_CONFIG_HOME }}/docker/config"

- name: Copy Docker daemon settings
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  become: yes

- name: Download Docker credentials helper
  unarchive:
    remote_src: yes
    src: "{{ docker.credentials_archive_url }}/v{{ docker.credentials_version }}/docker-credential-secretservice-v{{ docker.credentials_version }}-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0700
