---
# https://github.com/mattermost/desktop/issues/765#issuecomment-447322298
- name: Install missing Mattermost dependencies
  apt:
    name: "{{ item }}"
  become: yes
  loop:
    - libappindicator-dev

- name: Install Mattermost
  apt:
    deb: "{{ item }}"
  become: yes
  loop:
    - https://releases.mattermost.com/desktop/{{ mattermost.version }}/mattermost-desktop-{{ mattermost.version }}-linux-amd64.deb
