---
- name: Add Neovim PPA
  apt_repository:
    repo: "ppa:neovim-ppa/unstable"
  become: yes

- name: Install Neovim
  apt:
    name: neovim
  become: yes

- name: Create Neovim dirs
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ xdg.XDG_CONFIG_HOME }}/nvim"
    - "{{ xdg.XDG_DATA_HOME }}/nvim/site/autoload"

- name: Clone vim-plug
  git:
    repo: https://github.com/junegunn/vim-plug.git
    dest: "{{ xdg.XDG_DATA_HOME }}/vim-plug"

- name: Copy plug.vim into autoload folder
  copy:
    src: "{{ xdg.XDG_DATA_HOME }}/vim-plug/plug.vim"
    dest: "{{ xdg.XDG_DATA_HOME }}/nvim/site/autoload/"

- name: Copy init.vim into config folder
  copy:
    src: neovim/init.vim
    dest: "{{ xdg.XDG_CONFIG_HOME }}/nvim/init.vim"

- name: Install Neovim plugins
  shell: >
    nvim +'PlugInstall --sync' +qa
  changed_when: false  # it always registered as changed, so block it

- name: Set Neovim alternatives
  alternatives:
    link: "/usr/bin/{{ item }}"
    name: "{{ item }}"
    path: /usr/bin/nvim
  become: yes
  loop:
    - vi
    - vim
