---
# https://blog.tomecek.net/post/automount-with-systemd/
# https://rclone.org/onedrive/
- name: Check if rcone is installed
  shell: rclone -V
  ignore_errors: true
  register: rclone_version

- name: Install rclone
  shell: curl https://rclone.org/install.sh | bash
  become: yes
  when: rclone_version.stdout == ""

- name: Create mount point
  file:
    path: /media/onedrive
    state: directory
  become: yes

- name: Copy rclonefs mount helper script
  copy:
    src: onedrive/rclonefs
    dest: /usr/local/bin # can't go into .local/bin
    mode: 0755
  become: yes

- name: Copy systemd mount file
  template:
    src: media-onedrive.mount.j2
    dest: /etc/systemd/system/media-onedrive.mount
  become: yes

# NOTE: You must run `rclone config` manually before this step can run
# - name: Enable systemd mount
#   systemd:
#     name: media-onedrive.mount
#     enabled: yes
#     state: started
#   become: yes
