---
# https://blog.tomecek.net/post/automount-with-systemd/
- name: Install rclone
  apt:
    name: rclone
  become: yes

- name: Create mount point
  file:
    path: /media/onedrive
    state: directory
  become: yes

- name: Copy rclonefs mount helper script
  copy:
    src: onedrive/rclonefs
    dest: /usr/local/bin # can't go into .local/bin
    mode: 0755
  become: yes

- name: Copy systemd mount file
  template:
    src: media-onedrive.mount.j2
    dest: /etc/systemd/system/media-onedrive.mount
  become: yes

- name: Enable systemd mount
  systemd:
    name: media-onedrive.mount
    enabled: yes
    state: started
  become: yes
