---
- name: Install APT packages
  apt:
    name:
    - jq
    - dconf-editor
    - python-pip
    - flameshot
    - gufw
  become: yes

- name: Install Debian packages
  apt:
    deb: "{{ gitkraken.download_url }}"
  become: yes

- name: Install Pip packages
  pip:
    name: "{{ ansible_toolbox.download_url }}"
  become: yes

- name: Install snap packages
  snap:
    name:
      - mattermost-desktop
  become: yes

- name: Install classic snap packages
  snap:
    name: code
    classic: yes
  become: yes
