---
- name: Install APT packages
  apt:
    name: "{{ item }}"
  become: yes
  loop:
    - jq
    - dconf-editor
    - python-pip
    - flameshot

# can't point to gitkraken url because apt won't follow redirect to cdn
- name: Install Debian packages
  apt:
    deb: "{{ item }}"
  become: yes
  loop:
    - "{{ role_path }}/files/packages/mysql-connector-java"
    - https://release.axocdn.com/linux/gitkraken-amd64.deb

# install pip packages
- name: Install Pip packages
  pip:
    name: "{{ item }}"
  become: yes
  loop:
    - git+https://github.com/larsks/ansible-toolbox
