- name: Install packages
  apt:
    name:
    - tmux
    - tmuxinator

  become: yes

- name: Copy tmux config
  copy:
    src: tmux
    dest: '{{ xdg.XDG_CONFIG_HOME }}/'

- name: Create tmuxinator folders
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ xdg.XDG_CONFIG_HOME}}/tmuxinator'
    - '{{ xdg.XDG_DATA_HOME}}/tmuxinator'

- name: Download tmuxinator zsh completion script
  get_url:
    url: "{{ tmuxinator.zsh_completion_url }}"
    dest: '{{ xdg.XDG_DATA_HOME }}/tmuxinator/tmuxinator.zsh'
  become: yes

- name: Update zshrc
  blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK - tmux.yml'
    block: |
      export EDITOR=nvim
      alias tmux='tmux -f {{ xdg.XDG_CONFIG_HOME }}/tmux/tmux.conf'
      source {{ xdg.XDG_DATA_HOME }}/tmuxinator/tmuxinator.zsh
    dest: '{{ xdg.XDG_CONFIG_HOME }}/zsh/.zshrc'
