- name: Install packages
  apt:
    name:
    - tmux
    - ruby-full
  become: yes

- name: Copy tmux config
  copy:
    src: tmux
    dest: '{{ xdg.XDG_CONFIG_HOME }}/'

- name: Create tmuxinator folders
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ xdg.XDG_CONFIG_HOME}}/tmuxinator'
    - '{{ xdg.XDG_DATA_HOME}}/tmuxinator'

- name: Remove tmuxinator apt install if exists
  apt:
    name: tmuxinator
    state: absent
  become: yes

- name: Install tmuxinator gem
  gem:
    name: tmuxinator
    user_install: yes

- name: Download tmuxinator zsh completion script
  get_url:
    url: '{{ tmuxinator.zsh_completion_url }}'
    dest: '{{ xdg.XDG_DATA_HOME }}/tmuxinator/tmuxinator.zsh'
  become: yes

# PATH export syntax from https://guides.rubygems.org/faqs/#user-install
- name: Update zshrc
  blockinfile:
    marker: '# {mark} ANSIBLE MANAGED BLOCK - tmux.yml'
    block: |
      export PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
      export EDITOR=nvim
      alias tmux='tmux -f {{ xdg.XDG_CONFIG_HOME }}/tmux/tmux.conf'
      source {{ xdg.XDG_DATA_HOME }}/tmuxinator/tmuxinator.zsh
    dest: '{{ xdg.XDG_CONFIG_HOME }}/zsh/.zshrc'
