- name: Install Tmux
  apt:
    name: tmux
  become: yes

- name: Define tmux alias command that respects XDG
  lineinfile:
    dest: "{{ xdg.XDG_CONFIG_HOME }}/zsh/.zshrc"
    line: "alias tmux='tmux -f {{ xdg.XDG_CONFIG_HOME }}/tmux/tmux.conf'"

- name: Copy tmux config
  copy:
    src: tmux
    dest: "{{ xdg.XDG_CONFIG_HOME }}/"

